postgres:
  dialect: postgres
  datasource: host=${POSTGRES_HOST} port=${POSTGRES_PORT} dbname=${POSTGRES_DB_NAME} user=${POSTGRES_USERNAME} password=${POSTGRES_PASSWORD} sslmode=disable
  dir: migrations